version: '3.8'

networks: # wordpress로 네트워크 만들기
  wordpress:

services:
  php:
    #image: php:8.0-apache #직접 이미지를 받을 때 사용
    build:
      context: .   # .은 현재 디렉토리를 의미하므로 dockerfile을 사용해서 build 하겠다
      dockerfile: Dockerfile
    container_name: php  #컨테이너 네임 정해주기
    ports:
      - 80:80   #lccalhost에서 80포트로 docker container 80포트로 통신 
      # 여기도 php를 로컬로 사용하고 있다면 9000:9000 포트를 바꿔줘도 됨
    volumes:
      - ./default.conf:/etc/apache2/sites-enabled/000-default.conf  #최상위 디렉토리에 default.conf만들기
      - ./src:/var/www/html/   # ./src 는 현재디렉토리부터 src 서브디렉토리를 web service 디렉토리인 /var/www/html/ 연결
    networks: 
      - wordpress

  # Use root/example as user/password credentials
  mysql:
    image: mariadb:latest # 도커hub에서 이미지를 받아온다
    container_name: mysql
    restart: unless-stopped  #재시작하지 않음 unless-stopped 어떤 이유로 든지 멈추지 않으면 재시작 하지않음, 멈추면 재시작 
    ports: 
      - 3306:3306  # 포트를 로컬은 4306으로 설정한 이유는 이미 로컬에서 db가 돌아가고 있어서 4306으로 설정 없다면 3306:3306으로 하면 됨
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw  #root 패스워드가 됨 안써도 디폴트라고 하는 듯
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      SERVICE_TAGS: dev # 옵션 (없어도 무관)
    volumes:
      - ./mysqldata:/var/lib/mysql  # 데이터를 저장하려면 연결해줘야함 #mysql 디렉토리는 만들어야 함
    networks: 
      - wordpress

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST= mysql
      - PMA_PORT= 3306
    networks: 
      - wordpress

volumes:
  mysqldata: {}